### ISSUE TITLE
Нет метода для получения списка веток

### ISSUE THREAD

**Issue by nikehin** [markdown-ide/markdown_ide#13]
Думаю, что стоит добавить в ответ от **GET /api/projects/{id}** что-то похожее:
```
"branch": {
    "list": [ "master" ],
    "default": "master",
},
```

**Comment by may-cat** [comment]
Есть метод
`/api/projects/<projectCode>/branches`
Только он не обдокан, сейчас поправлю

**Comment by nikehin** [comment]
Да, благодарю.
